#!/bin/sh

UPLOAD_HOST="rshen@172.16.1.1"
UPLOAD_DIR="/data/fsroot/AppJails-images"
HTTP_URLBASE="http://172.16.1.29/AppJail-images"

makejail () {
    local _j

    _j="$1"
    (cd "$_j" && \
	 sudo appjail makejail \
	      -f build.makejail \
	      -j "$_j" \
	      -o virtualnet="ajnet:$_j default" \
	      -o nat)
}

exportjail() {
    local _j _tag

    _j="$1"
    _tag="$2"

    if [ "$_tag" ]; then
	_tag=14.1
    fi
    
    sudo appjail stop "$_j" && \
	sudo appjail image export -f -t "$_tag" "$_j" 
}

uploadjail() {
    local _j _tag

    _j="$1"
    _tag="$2"

    (cd /usr/local/appjail/cache/images && tar cf - "$_j/$_tag-amd64-image.appjail") | \
	ssh $UPLOAD_HOST "sudo tar -C $UPLOAD_DIR xvf -"

    cp /usr/local/appjail/cache/images/$_j/.ajspec $_j

    sudo appjail image metadata set -t "$_tag" \
	 -f $_j/.ajspec source:amd64+="$HTTP_URLBASE/$_j/$_tag-amd64-image.appjail"

    git add $_j/.ajspec
    git commit -m "update ajspec for $_j"

    git push
}

mk_image() {
    local _j _tag

    _j="$1"
    _tag="$2"

    if [ ! -f "$_j"/build.makejail ]; then
	echo no build.makejail found under $_j
	exit 2
    fi
    
    makejail "$_j"  "$_tag" && \
	exportjail "$_j" "$_tag" && \
	uploadjail "$_j" "$_tag"
}

usage() {
    cat <<EOF
Usage: mkimage [-f config] jail [tag]
EOF
}


jname=""
tag=""
conf=""

args=$(getopt "hf:" $*)

if [ $? -ne 0 ]; then
    usage
    exit 1
fi

set -- $args

while [ $# -gt 0 ]; do
    case "$1" in
	-f)
	    conf="$2"
	    shift
	    ;;
	--)
	    shift
	    break
    esac
done

if [ $# -gt 0 ]; then
    jname="$1"
    shift
fi

if [ $# -gt 0 ]; then
    tag="$1"
    shift
fi

if [ -z "$jname" ]; then
    usage
    exit 1
fi

if [ ! -z "$conf" -a -r "$conf" ]; then
    . $conf
fi

if [ -z "$tag" ]; then
    tag="14.1"
fi

mk_image "$jname" "$tag"
